# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
  - name: DS_CLOUDWATCH # name of the datasource
    type: cloudwatch # type of the data source
    access: proxy # make grafana perform the requests
    org_id: 1 # id of the organization to tie this datasource to
    isDefault: true # <bool> mark as default datasource. Max one per org
    jsonData: # <map> fields that will be converted to json and stored in json_data
      authType: default
      assumeRoleArn: $DS_ROLE
      defaultRegion: $DS_REGION
    editable: false # whether it should be editable
    version: 1
